### PR TITLE
fix: Flush() should flush underlying avro writer (#196)

### LINKED ISSUE #196: ocf encoder's Flush() does not write out *just* the header
If I wanted to write an empty Avro file (zero blocks, header only), we currently can't. The result is a zero-byte file.

In my opinion, it's useful to create a non-zero length file with zero records, if one only wants to convey the structure (i.e. schema).

The problem is that the encoder's `Flush` function will check for `e.count == 0` and immediately exit, instead of also flushing the underlying `e.writer`. And because `writer` is not exposed, we can't flush it manually in a different way.

### PR DESCRIPTION
**Pull request by mibanescu**
This is useful when one wants a file with *just* the Avro header, for instance in order to convey the schema and no records.

Fixes #196

### CODE REVIEW

File: ocf/ocf.go [hunk 1]
```diff
@@ -292,7 +292,7 @@ func (e *Encoder) Encode(v interface{}) error {
 // Flush flushes the underlying writer.
 func (e *Encoder) Flush() error {
 	if e.count == 0 {
-		return nil
+		return e.writer.Flush()
```
Comment (nrwiersma) [inline ocf/ocf.go:295]: This is not the correct fix for #196. Instead you should flush after writing the header.

**Review by nrwiersma — CHANGES_REQUESTED** [review]

File: ocf/ocf.go (hunk 1 above)
Comment (mibanescu) [reply ocf/ocf.go]: Fixed.

**Review by nrwiersma — APPROVED** [review]
LGTM 👏🏻
